spring.application.name=shipment-service


server.port=8081

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/delivery
spring.datasource.username=delivery
spring.datasource.password=delivery
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Swagger
